# action.yml
name: 'ECS Run Task'
description: 'Execute an ECS task'
inputs:
  task-name:
    description: 'ECS task[:revision]'
    required: true
  cluster:
    description: 'ECS Cluster to run task on'
    required: false
    default: default
  wait:
    description: 'Wait for ECS task to complete'
    required: true
    default: false
  timeout:
    description: 'Timeout when waiting for completition'
    default: 600
  debug:
    description: 'Enable debugging'
    default: false
  aws-role-arn:
    description: 'AWS IAM Role to assume (optional)'
  aws-external-id:
    description: 'External ID to use when assuming roles (optional)'

outputs:
  status:
    description: 'Exit status of container'

runs:
  using: 'docker'
  image: 'Dockerfile'
