# action.yml
name: 'ECS Run Task'
description: 'Syncronously execute an ECS task'
inputs:
  aws-access-key-id:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws-secret-access-key:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
  aws-region:
    description: 'AWS_REGION'
    required: true
    default: us-west-2
  aws-role-arn:
    description: 'AWS IAM Role to assume (optional)'
  aws-external-id:
    description: 'External ID to use when assuming roles (optional)'
  task-name:
    description: 'ECS task[:revision]'
    required: true
  wait:
    description: 'Wait for ECS task to complete'
    required: true
    default: false
  timeout:
    description: 'Timeout when waiting for completition'
    default: 600
  debug:
    description: 'Enable debugging'
    default: false

outputs:
  status:
    description: 'Exit status of container'

runs:
  using: 'docker'
  image: 'Dockerfile'
