# action.yml
name: 'ECS Run Task'
description: 'Execute an ECS task'
inputs:
  task-name:
    description: 'ECS task[:revision]'
    required: true
  wait:
    description: 'Wait for ECS task to complete'
    required: true
    default: false
  timeout:
    description: 'Timeout when waiting for completition'
    default: 600
  debug:
    description: 'Enable debugging'
    default: false

outputs:
  status:
    description: 'Exit status of container'

runs:
  using: 'docker'
  image: 'Dockerfile'
